# Generated by Django 3.1 on 2021-03-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210329_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ctegory',
            new_name='category',
        ),
    ]
